local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Horde" then return end
if ZGV:DoMutex("LevelingHLEGION") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Death Knight\\Death Knight Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Death Knight\\Death Knight Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Death Knight\\Death Knight 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Demon Hunter\\Demon Hunter Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Demon Hunter\\Demon Hunter Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Demon Hunter\\Demon Hunter 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Druid\\Druid Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Druid\\Druid Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Druid\\Druid 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Evoker\\Evoker Intro")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Hunter\\Hunter Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Hunter\\Hunter Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Hunter\\Hunter 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Mage\\Mage Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Mage\\Mage Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Mage\\Mage 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Monk\\Monk Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Monk\\Monk Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Monk\\Monk 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Paladin\\Paladin Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Paladin\\Paladin Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Paladin\\Paladin 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Priest\\Priest Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Priest\\Priest Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Priest\\Priest 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Rogue\\Rogue Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Rogue\\Rogue Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Rogue\\Rogue 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Shaman\\Shaman Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Shaman\\Shaman Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Shaman\\Shaman 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warlock\\Warlock Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warlock\\Warlock Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warlock\\Warlock 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warrior\\Warrior Intro & Artifacts")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warrior\\Warrior Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warrior\\Warrior 7.20 Order Hall Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Azsuna")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Highmountain")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Stormheim")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Suramar (45-70)")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Val'sharah")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Broken Shore Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Argus Campaign")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Argus Vindicaar Mission Table Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Balance of Power Questline")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Legion Invasions")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Broken Shore\\Excavator Karla Quests")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Dalaran Postmaster Quest Line")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Rogue Pickpocketing Quest Line")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Meatball Order Hall Champion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\The Hunt For Illidan Stormrage")
