local ADDON_NAME, SW = ...
SW = SW or {}
local C = {}

C.INTERFACE = 110200
C.ADDON_NAME = ADDON_NAME
C.VERSION = "1.0"
C.AUTHOR = "OpenAI"
C.SAVED_VAR = "SmartWeaverDB"

C.ROLES = { DPS = "DAMAGER", HEALER = "HEALER", TANK = "TANK" }
C.PRIMARY_STATS = {
    STRENGTH = "ITEM_MOD_STRENGTH_SHORT",
    AGILITY = "ITEM_MOD_AGILITY_SHORT",
    INTELLECT = "ITEM_MOD_INTELLECT_SHORT",
    STAMINA = "ITEM_MOD_STAMINA_SHORT",
}
C.SECONDARY_STATS = {
    CRIT = "ITEM_MOD_CRIT_RATING_SHORT",
    HASTE = "ITEM_MOD_HASTE_RATING_SHORT",
    MASTERY = "ITEM_MOD_MASTERY_RATING_SHORT",
    VERSATILITY = "ITEM_MOD_VERSATILITY",
    LEECH = "ITEM_MOD_LEECH_RATING_SHORT",
    AVOIDANCE = "ITEM_MOD_AVOIDANCE_RATING_SHORT",
    SPEED = "ITEM_MOD_SPEED_RATING_SHORT",
}

C.COLD_START_SAMPLES = 20
C.HISTORY_MAX = 100
C.FORGET = 0.99
C.RIDGE = 0.001
C.EPSILON = 0.05

SW.Const = C
return C
