name: Lua Tests
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Lua 5.1 for pure-Lua tests/specs
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Show Lua version
        run: lua -v

      - name: Discover *_spec.lua files
        id: discover
        shell: bash
        run: |
          set -e
          specs="$(git ls-files '*_spec.lua' || true)"
          if [ -z "$specs" ]; then
            echo "No *_spec.lua files found. Failing to surface misconfiguration." >&2
            exit 1
          fi
          printf '%s\n' "$specs" > _spec_list.txt
          echo "found=$(wc -l < _spec_list.txt | tr -d ' ')" >> $GITHUB_OUTPUT
          echo "Discovered specs:"; cat _spec_list.txt

      - name: Run specs
        if: steps.discover.outcomes != 'failure'
        shell: bash
        run: |
          set -e
          while IFS= read -r s; do
            echo "::group::Running $s"
            lua "$s"
            echo "::endgroup::"
          done < _spec_list.txt

      - name: Upload spec list (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lua-spec-list
          path: _spec_list.txt
